import { test, expect, type Page } from '@playwright/test'
import { loadQuestions } from '../../server/questions.js'
import type { TeamState } from '../../shared/domain.js'
const bank = loadQuestions('./questions')
async function join(page: Page, code: string) { await page.goto('/'); await page.getByLabel('Team code').fill(code); await page.getByRole('button', { name: 'Join', exact: true }).click(); await expect(page.getByRole('heading', { level: 1 })).toBeVisible() }
async function chooseCorrect(page: Page, subject: 'physics' | 'chemistry' | 'biology', index: number) { const q = bank[subject]['11–13'][index]; if (q.type === 'multiple-choice') await page.locator('.choice').nth(q.correctIndex).click(); else await page.getByLabel('Your answer').fill(q.type === 'text' ? q.acceptedAnswers[0] : String(q.numericAnswer)) }
test('real browser: admin, multiple sessions, subject progress, shared game and responsive layout', async ({ browser, page }, testInfo) => {
  const pageErrors: string[] = []; page.on('pageerror', e => pageErrors.push(e.message))
  await page.goto('/admin'); await page.getByLabel('Admin password').fill('browser-test-password'); await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('button', { name: 'Add team', exact: true }).click();
  await page.getByLabel('Team name').fill('Photon Pigeons'); await page.getByLabel('Login code').fill('K7MP'); await page.getByRole('button', { name: 'Create team', exact: true }).click()
  await expect(page.getByRole('row', { name: /Photon Pigeons/ })).toBeVisible()
  await page.getByRole('button', { name: 'Add team', exact: true }).click();
  await page.getByLabel('Team name').fill('Older Owls'); await page.getByLabel('Age category').selectOption('17–18'); await page.getByLabel('Login code').fill('OWL7'); await page.getByRole('button', { name: 'Create team', exact: true }).click()
  await expect(page.getByRole('row', { name: /Older Owls/ })).toBeVisible()
  const contextA = await browser.newContext(), contextB = await browser.newContext(), contextC = await browser.newContext()
  const a = await contextA.newPage(), b = await contextB.newPage(), c = await contextC.newPage()
  for (const p of [a,b,c]) p.on('pageerror', e => pageErrors.push(e.message))
  await join(a, 'k7mp'); await join(b, 'K7MP'); await join(c, 'OWL7')
  await expect(a.getByRole('heading', { level: 1 })).toHaveText('Waiting for the start…')
  await expect(b.getByRole('heading', { level: 1 })).toHaveText('Waiting for the start…')
  await expect(a.getByRole('timer')).toHaveText('60:00')
  await expect(page.getByRole('timer')).toHaveText('60:00')
  await a.getByRole('link', { name: /^Game/ }).click()
  await expect(a.getByRole('heading', { level: 1 })).toHaveText('Waiting for the start…')
  await expect(a.locator('svg.sea')).toHaveCount(0)
  await a.getByRole('link', { name: 'Questions', exact: true }).click()
  await a.screenshot({ path: testInfo.outputPath('waiting.png'), fullPage: true })
  await page.getByRole('button', { name: 'Start game', exact: true }).click()
  await expect(a.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][0].prompt)
  await expect(a.getByRole('timer')).toHaveText(/59:[0-5][0-9]/)
  const booklet = a.getByRole('link', { name: /Booklet/ })
  await expect(booklet).toHaveAttribute('href', 'https://www.cygnusinternational.org/uploads/pdf/hbm6rSO9t5tdwQpUdwHjIbBjwTzUagQ3YB2ftRf3.pdf')
  await expect(booklet).toHaveAttribute('target', '_blank')
  // Intercept the external PDF so this check needs no internet or download.
  await contextA.route('https://www.cygnusinternational.org/**', route => route.fulfill({ contentType: 'text/html', body: '<p>Booklet</p>' }))
  const [bookletTab] = await Promise.all([contextA.waitForEvent('page'), booklet.click()])
  await bookletTab.waitForLoadState(); expect(bookletTab.url()).toContain('cygnusinternational.org'); await bookletTab.close()
  await a.getByRole('button', { name: 'ESS', exact: true }).click()
  await expect(a.getByRole('link', { name: /Booklet/ })).toHaveCount(0)
  await a.getByRole('button', { name: 'Physics', exact: true }).click()
  await expect(c.getByRole('heading', { level: 1 })).toHaveText(bank.physics['17–18'][0].prompt)
  await chooseCorrect(a, 'physics', 0); await a.getByRole('button', { name: 'Submit answer' }).click()
  await expect(a.getByRole('status')).toContainText('Correct · +10 Research')
  await expect(b.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][1].prompt)
  // 10 starting Research plus 10 for the answer.
  await expect(b.locator('.research')).toContainText('20')
  await a.getByRole('button', { name: /^Chemistry/ }).click(); await b.getByRole('button', { name: /^Biology/ }).click()
  await chooseCorrect(a, 'chemistry', 0); await chooseCorrect(b, 'biology', 0)
  await Promise.all([a.getByRole('button', { name: 'Submit answer' }).click(), b.getByRole('button', { name: 'Submit answer' }).click()])
  await expect(a.locator('.research')).toContainText('40'); await expect(b.locator('.research')).toContainText('40')
  await a.getByRole('button', { name: /^Physics/ }).click(); await expect(a.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][1].prompt)
  await a.reload(); await expect(a.locator('.team-heading')).toContainText('Photon Pigeons')
  await a.screenshot({ path: testInfo.outputPath('questions-desktop.png'), fullPage: true })
  await a.getByRole('link', { name: /^Game/ }).click(); await c.getByRole('link', { name: /^Game/ }).click()
  // Two teams: a fishing ground each, two spare and one golden. The boat waits in the harbour, and the Game tab says so.
  const list = (p: Page) => p.getByRole('region', { name: 'Fishing grounds' }).getByRole('button')
  await expect(list(a)).toHaveCount(5)
  await expect(a.locator('.hud-status')).toHaveText('Idle. Tap a fishing ground on the map to send your boat.')
  // Only the frame loop moves boats: no CSS transition fights it.
  expect(await a.locator('.boat').first().evaluate(el => getComputedStyle(el).transitionProperty)).not.toContain('transform')
  await expect(a.locator('.tab-alert')).toHaveCount(1)
  const pigeons = async (p: Page) => ((await (await p.request.get('/api/team/state')).json()) as TeamState).game.boats.find(boat => boat.name === 'Photon Pigeons')!
  // On a slow network, orders given while one is in flight wait, and only the latest follows.
  const orders: unknown[] = []; a.on('request', r => { if (r.url().endsWith('/api/team/game/order')) orders.push(r.postDataJSON()) })
  let release = () => {}; const held = new Promise<void>(resolve => { release = resolve })
  await a.route('**/api/team/game/order', async route => { const response = await route.fetch(); await held; await route.fulfill({ response }) }, { times: 1 })
  for (const i of [0, 1, 2]) await list(a).nth(i).click()
  await expect(a.locator('.hud-status')).toContainText('Sending…')
  expect(orders).toHaveLength(1)
  release()
  await expect(a.locator('.hud-status')).not.toContainText('Sending…')
  expect(orders).toHaveLength(2)
  expect(orders[1]).not.toEqual(orders[0])
  // Every team sees the boat's order at once.
  expect((await pigeons(c)).target).toEqual(orders[1])
  await expect(a.locator('.hud-status')).toContainText(/^Sailing to a fishing ground/)
  await expect(a.locator('.tab-alert')).toHaveCount(0)
  // A minute on, the boat has burnt Research getting there and is fishing.
  await a.request.post('/__test/rewind/60000')
  await expect(a.locator('.hud-status')).toContainText(/^Fishing: next fish in about \d+ s/)
  expect(Number(await a.locator('.hud-fuel strong').textContent())).toBeLessThan(40)
  // The bait switch is its own order, and it stays on.
  await a.getByRole('switch', { name: 'Bait' }).check()
  await expect.poll(async () => ((await (await a.request.get('/api/team/state')).json()) as TeamState).game.own.bait).toBe(true)
  await a.request.post('/__test/rewind/10000')
  await expect(a.locator('.hud-score strong')).not.toHaveText('0')
  await a.screenshot({ path: testInfo.outputPath('game-desktop.png'), fullPage: true })
  // A tap on open sea (the harbour) sends the boat there, which stops the catch.
  const box = (await a.locator('svg.sea').boundingBox())!, map = ((await (await a.request.get('/api/team/state')).json()) as TeamState).game.map!, harbour = map.harbour
  await a.locator('svg.sea').click({ position: { x: (harbour.x + 0.5) / map.width * box.width, y: (harbour.y + 0.5) / map.height * box.height } })
  await expect.poll(async () => (await pigeons(a)).target).toEqual(harbour)
  await expect(a.locator('.hud-status')).toContainText(/^Sailing: /)
  const score = (await a.locator('.hud-score strong').textContent())!
  await c.getByRole('link', { name: 'Standings', exact: true }).click()
  await expect(c.getByRole('region', { name: 'Scores' }).getByRole('row', { name: /Photon Pigeons/ }).getByRole('cell')).toHaveText(score)
  // Orders still waiting when a device signs out are dropped: they never go out with the next team's session.
  await b.getByRole('link', { name: /^Game/ }).click()
  const sent: unknown[] = []; b.on('request', r => { if (r.url().endsWith('/api/team/game/order')) sent.push(r.postDataJSON()) })
  let deliver = () => {}, delivered = () => {}; const orderHeld = new Promise<void>(r => { deliver = r }), landed = new Promise<void>(r => { delivered = r })
  await b.route('**/api/team/game/order', async route => { const response = await route.fetch(); await orderHeld; await route.fulfill({ response }); delivered() }, { times: 1 })
  await list(b).nth(0).click()
  await expect(b.locator('.hud-status')).toContainText('Sending…')
  const first = sent[0]
  await list(b).nth(1).click()
  await b.getByRole('button', { name: 'Leave', exact: true }).click()
  await b.getByLabel('Team code').fill('OWL7'); await b.getByRole('button', { name: 'Join', exact: true }).click()
  await expect(b.locator('.team-heading')).toContainText('Older Owls')
  // The held response arrives for the old session, then a poll completes for the new one.
  deliver(); await landed; await b.waitForResponse(r => r.url().endsWith('/api/team/state'))
  expect(sent).toEqual([first])
  await expect(b.locator('.team-heading')).toContainText('Older Owls')
  const boatsAfter = ((await (await b.request.get('/api/team/state')).json()) as TeamState).game.boats.map(boat => [boat.name, boat.target])
  expect(boatsAfter).toEqual([['Older Owls', null], ['Photon Pigeons', first]])
  await a.getByRole('link', { name: 'Questions', exact: true }).click(); await expect(a.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][1].prompt)
  await a.setViewportSize({ width: 390, height: 844 }); await a.screenshot({ path: testInfo.outputPath('questions-mobile.png'), fullPage: true })
  expect(await a.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await a.getByRole('button', { name: 'Skip question', exact: true }).scrollIntoViewIfNeeded(); expect(await a.locator('.research').evaluate(el => el.getBoundingClientRect().top)).toBeGreaterThanOrEqual(0); await a.getByRole('button', { name: 'Skip question', exact: true }).click(); await a.getByRole('button', { name: 'Yes, skip' }).click(); await expect(a.getByText('4 team skips left')).toBeVisible()
  // Phones turn the map a quarter, so it fills a tall screen.
  await a.getByRole('link', { name: /^Game/ }).click(); await expect(a.locator('svg.sea')).toHaveAttribute('viewBox', '0 0 10 16')
  await a.screenshot({ path: testInfo.outputPath('game-mobile.png'), fullPage: true }); expect(await a.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect(page.getByRole('row', { name: /Photon Pigeons/ }).getByRole('cell').nth(3)).toHaveText(score)
  await page.screenshot({ path: testInfo.outputPath('admin.png'), fullPage: true })
  await a.getByRole('link', { name: 'Standings', exact: true }).click()
  await expect(a.getByRole('heading', { name: 'Standings', exact: true })).toBeVisible()
  await expect(a.getByRole('region', { name: 'Scores' }).getByRole('row', { name: /Photon Pigeons/ }).getByRole('cell')).toHaveText(score)
  await a.screenshot({ path: testInfo.outputPath('standings-mobile.png'), fullPage: true })
  expect(await a.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  // The game above moved the shared start 70 seconds back.
  await a.reload(); await expect(a.getByRole('timer')).toHaveText(/5[78]:[0-5][0-9]/)
  await a.getByRole('link', { name: 'Questions', exact: true }).click()
  await contextA.route('**/api/team/state', async route => {
    const response = await route.fetch(), body = await response.json()
    body.standings.frozenAt = Date.now()
    await route.fulfill({ response, json: body })
  })
  await a.getByRole('link', { name: 'Standings', exact: true }).click()
  await expect(a.getByText('Frozen for the final 5 minutes.', { exact: true })).toBeVisible()
  await a.reload()
  await expect(a.getByText('Frozen for the final 5 minutes.', { exact: true })).toBeVisible()
  await contextA.unroute('**/api/team/state')
  // An authoritative expiry response should immediately replace either view.
  await contextA.route('**/api/**', async route => {
    const path = new URL(route.request().url()).pathname
    if (!['/api/competition', '/api/team/state'].includes(path)) return route.continue()
    const response = await route.fetch(), body = await response.json()
    const clock = path === '/api/competition' ? body : body.competition
    clock.status = 'finished'; clock.endsAt = clock.serverNow - 1
    await route.fulfill({ response, json: body })
  })
  await expect(a.getByRole('heading', { level: 1 })).toHaveText('Competition over.')
  await expect(a.getByRole('region', { name: 'Scores' })).toHaveCount(0)
  await expect(a.getByRole('timer')).toHaveText('00:00')
  await expect(a.getByRole('button', { name: 'Submit answer' })).toHaveCount(0)
  await a.getByRole('link', { name: /^Game/ }).click()
  await expect(a.locator('svg.sea')).toHaveCount(0)
  await a.getByRole('link', { name: 'Standings', exact: true }).click()
  await expect(a.getByRole('heading', { level: 1 })).toHaveText('Competition over.')
  await expect(a.getByRole('region', { name: 'Scores' })).toHaveCount(0)
  expect(pageErrors).toEqual([])
  await contextA.close(); await contextB.close(); await contextC.close()
})
test('invalid code and offline failures are understandable', async ({ page }) => {
  await page.goto('/'); await page.getByLabel('Team code').fill('ZZZZ'); await page.getByRole('button', { name: 'Join', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('That code was not found')
  await page.route('**/api/team/login', route => route.abort()); await page.getByRole('button', { name: 'Join', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('Cannot reach the server')
})

test('Czech UI and grading share progress without changing drafts or attempts', async ({ browser, page }, testInfo) => {
  const headers = { 'X-Competition-Client': '1' }
  await page.request.post('/api/admin/login', { headers, data: { password: 'browser-test-password' } })
  await page.request.post('/api/admin/teams', { headers, data: { name: 'Czech team', age: '11–13', code: 'CZ11' } })
  const competition = await (await page.request.get('/api/competition')).json()
  if (competition.status === 'waiting') await page.request.post('/api/admin/start', { headers, data: {} })
  const otherContext = await browser.newContext()
  const other = await otherContext.newPage()
  await join(other, 'CZ11')
  await page.goto('/')
  await page.getByLabel('Language / Jazyk').selectOption('cs')
  await expect(page.locator('html')).toHaveAttribute('lang', 'cs')
  await page.getByLabel('Kód týmu').fill('CZ11')
  await page.getByRole('button', { name: 'Připojit se', exact: true }).click()
  const first = bank.physics['11–13'][0]
  expect(first.type).toBe('multiple-choice')
  if (first.type !== 'multiple-choice') throw new Error('Expected MC fixture')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(first.cs.prompt)
  await page.locator('.choice').nth(first.correctIndex).click()
  await page.getByLabel('Language / Jazyk').selectOption('en')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(first.prompt)
  await expect(page.getByRole('radio').nth(first.correctIndex)).toBeChecked()
  await page.getByLabel('Language / Jazyk').selectOption('cs')
  await expect(page.getByRole('radio').nth(first.correctIndex)).toBeChecked()
  const unchanged = await (await page.request.get('/api/team/state')).json()
  expect(unchanged.progress.physics.attempts).toBe(0)
  expect(unchanged.team.research).toBe(10)
  await page.getByRole('button', { name: 'Odeslat odpověď' }).click()
  await expect(page.getByRole('status')).toContainText('Správně · +10 Výzkum')
  await expect(other.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][1].prompt)
  await expect(other.getByLabel('Language / Jazyk')).toHaveValue('en')
  await expect(other.locator('.research')).toContainText('20 Research')
  await page.getByRole('button', { name: 'Biologie', exact: true }).click()
  const bio = bank.biology['11–13'][0]
  if (bio.type !== 'multiple-choice') throw new Error('Expected MC fixture')
  await page.locator('.choice').nth(bio.correctIndex).click()
  await page.getByRole('button', { name: 'Odeslat odpověď' }).click()
  await page.getByLabel('Vaše odpověď').fill('60,0')
  await page.getByLabel('Language / Jazyk').selectOption('en')
  await expect(page.getByLabel('Your answer')).toHaveValue('60,0')
  await page.getByLabel('Language / Jazyk').selectOption('cs')
  await page.getByRole('button', { name: 'Odeslat odpověď' }).click()
  await expect(page.getByRole('status')).toContainText('Správně · +10 Výzkum')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(bank.biology['11–13'][2].cs.prompt)
  await chooseCorrect(other, 'physics', 1)
  await other.getByRole('button', { name: 'Submit answer' }).click()
  await page.getByRole('button', { name: 'Fyzika', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][2].cs.prompt)
  await page.getByLabel('Vaše odpověď').fill('5,0')
  await page.getByRole('button', { name: 'Odeslat odpověď' }).click()
  await expect(page.getByRole('status')).toContainText('Správně · +10 Výzkum')
  await page.reload()
  await expect(page.getByLabel('Language / Jazyk')).toHaveValue('cs')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][3].cs.prompt)
  await page.getByLabel('Vaše odpověď').fill('  dolů  ')
  await page.getByRole('button', { name: 'Odeslat odpověď' }).click()
  await expect(page.locator('.research')).toContainText('70 Výzkum')
  await expect(other.locator('.research')).toContainText('70 Research')
  // Czech scientific text and code output both work, even after switching UI language.
  const csTrack = bank['computer-science']['11–13']
  const textIndex = csTrack.findIndex(q => q.id === 'computer-science-11-09')
  expect(textIndex).toBeGreaterThanOrEqual(0)
  for (const q of csTrack.slice(0, textIndex)) {
    const answer = q.type === 'multiple-choice' ? String(q.correctIndex) : q.type === 'numerical' ? String(q.numericAnswer) : q.acceptedAnswers[0]
    const response = await page.request.post('/api/team/answer', { headers, data: { subject: 'computer-science', questionId: q.id, answer } })
    expect(response.ok()).toBe(true)
  }
  await page.getByRole('button', { name: 'Informatika', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(csTrack[textIndex].cs.prompt)
  await page.getByLabel('Vaše odpověď').fill('  ne  ')
  await page.getByLabel('Language / Jazyk').selectOption('en')
  await expect(page.getByLabel('Your answer')).toHaveValue('  ne  ')
  await page.getByRole('button', { name: 'Submit answer' }).click()
  await expect(page.getByRole('status')).toContainText('Correct · +10 Research')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(csTrack[textIndex + 1].prompt)
  await page.getByLabel('Language / Jazyk').selectOption('cs')
  await expect(other.locator('.research')).toContainText('170 Research')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('czech-questions-mobile.png'), fullPage: true })
  await page.getByRole('link', { name: /^Hra/ }).click()
  const czechList = page.getByRole('region', { name: 'Loviště' }).getByRole('button')
  await expect(czechList.first()).toHaveText(/^(Zlaté l|L)oviště \d+\/\d+ · .+\d+ políč(ko|ka|ek) · cesta vyložit a zpět: výzkum \d+/)
  await expect(page.locator('.hud-status')).toHaveText('Kotví. Klepnutím na loviště v mapě tam pošlete svou loď.')
  await expect(page.getByRole('switch', { name: 'Návnada' })).not.toBeChecked()
  await expect(page.getByText('Jak hrát', { exact: true })).toBeVisible()
  await expect(page.locator('.hud-fuel .hud-sub')).toHaveText('výzkum; 1 za políčko')
  await page.getByRole('link', { name: 'Pořadí', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Pořadí' })).toBeVisible()
  await page.goto('/admin')
  await expect(page.getByRole('heading', { name: 'Týmy', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Přidat tým' })).toBeVisible()
  await otherContext.close()
})

test('the admin dashboard and its reset stay reachable when the roster cannot load', async ({ page }) => {
  // As when game catch-up fails on the server: past the admin check, the roster read answers 500.
  const failure = 'The server could not complete this request. Please try again.'
  await page.route('**/api/admin/teams', async route => {
    if (route.request().method() !== 'GET') return route.continue()
    const response = await route.fetch()
    await route.fulfill(response.status() === 401 ? { response } : { status: 500, json: { error: failure } })
  })
  await page.goto('/admin'); await page.getByLabel('Admin password').fill('browser-test-password'); await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Teams', exact: true })).toBeVisible()
  await expect(page.getByRole('alert')).toHaveText(failure)
  await expect(page.getByText('No teams yet.')).toHaveCount(0)
  // A reload (or another device) still opens the dashboard rather than the sign-in form.
  await page.reload()
  // One confirmation, no typing.
  page.once('dialog', dialog => { expect(dialog.message()).toContain('Reset the competition?'); void dialog.accept() })
  await page.getByRole('button', { name: 'Reset competition…' }).click()
  await expect(page.getByRole('button', { name: 'Start game', exact: true })).toBeVisible()
  await expect(page.getByLabel('Admin password')).toHaveCount(0)
})
